name: Python application

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pypiwin32
    - name: Test windows executable files
      run: |
        pip install pytest
        pyinstaller --onefile main_flask.py
        copy /b dist\main_flask.exe main-win.exe
        rmdir dist /s
        rmdir build /s
        ping -n 5 127.0.0.1
        pyinstaller --onefile start.py
        copy /b dist\start.exe start.py
        START /B main-win.exe
        ping -n 5 127.0.0.1
        python -m unittest discover tests/rest-win "*_test.py"


